"""Add reset_token and reset_token_expires_at to users

Revision ID: 1d5bbfd45112
Revises: 9a3c4d2e1f00
Create Date: 2026-05-27 15:14:08.353292

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5bbfd45112'
down_revision: Union[str, None] = '9a3c4d2e1f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledgers', 'cert_expiry_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index('ix_research_sources_notebook_id', table_name='research_sources')
    op.drop_index('ix_research_sources_status', table_name='research_sources')
    op.drop_constraint('research_sources_notebook_id_fkey', 'research_sources', type_='foreignkey')
    op.create_foreign_key(None, 'research_sources', 'research_notebooks', ['notebook_id'], ['id'], ondelete='cascade')
    op.drop_constraint('system_settings_category_key_key', 'system_settings', type_='unique')
    op.create_index(op.f('ix_system_settings_category'), 'system_settings', ['category'], unique=False)
    op.create_unique_constraint('uq_category_key', 'system_settings', ['category', 'key'])
    op.add_column('users', sa.Column('reset_token', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_column('users', 'reset_token_expires_at')
    op.drop_column('users', 'reset_token')
    op.drop_constraint('uq_category_key', 'system_settings', type_='unique')
    op.drop_index(op.f('ix_system_settings_category'), table_name='system_settings')
    op.create_unique_constraint('system_settings_category_key_key', 'system_settings', ['category', 'key'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'research_sources', type_='foreignkey')
    op.create_foreign_key('research_sources_notebook_id_fkey', 'research_sources', 'research_notebooks', ['notebook_id'], ['id'])
    op.create_index('ix_research_sources_status', 'research_sources', ['status'], unique=False)
    op.create_index('ix_research_sources_notebook_id', 'research_sources', ['notebook_id'], unique=False)
    op.alter_column('ledgers', 'cert_expiry_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
